<hr>
<table WIDTH=100%; style="BORDER-WIDTH: 0px; FONT-SIZE:12px;" >
<tr align="center">
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=MK">Á¦Á¶»ç</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=SP">Shape</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=BT">Body Types</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=PT">Point Types</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=NL">Needle Length</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=LT">Length</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=CR">Colour</a></b><br>
</td>
<td bgcolor="#EEEEEE">
<b><a href="code_list.php?parent=SZ">Size</a></b><br>
</td>
</tr>
</table>
<hr>