<?
	//////////////////////////////////////////////////////////////
	//
	// 	Date 		: 2004/03/02
	// 	Last Update : 2004/03/02
	// 	Author 		: Park, ChanHo
	// 	History 	: 2004.03.02 by Park ChanHo 
	// 	File Name 	: global_init.inc
	// 	Description : 관리자 global 변수
	// 	Version 	: 1.0
	//
	//////////////////////////////////////////////////////////////

	$g_site_title = "::::: U:COMPANION Project :::::";
	$g_site_name = "U:COMPANION";
	$g_site_url = "http://U:COMPANION.co.kr";
?>
